icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#251c1f"
idle_fg = "#dd95ad"

good_bg = "#251c1f"
good_fg = "#dd95ad"

warning_bg = "#8d2e4d"
warning_fg = "#f1d2dc"

critical_bg = "#de6f6f"
critical_fg = "#251c1f"

info_bg = "#251c1f"
info_fg = "#dd95ad"

separator = "\ue0ba"

[icons]
icons = "material-nf"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:50,rot_interval:0.5) $prev $play $next |}"

[[block]]
block = "cpu"

[[block]]
block = "memory"
format = " $icon $mem_used_percents"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
format = " $icon $available "
format_alt = " $icon $available / $total ($percentage)"
[[block.click]]
button = "right"
update = true

[[block]]
block = "battery"
format = " $icon $percentage ($time)"
full_format = " $icon $percentage"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%F %H:%M:%S') "
