# Neovim Stuff
brew "neovim"
brew "ripgrep"
brew "fd"
brew "lua-language-server"

# Terminal Stuff
brew "starship"
brew "tmux"
brew "ranger"
brew "overmind"
brew "bat"
brew "direnv"

# Tmux Stuff
brew "entr"

# Version Managers
brew "git"
brew "rtx"

# Other
brew "gnupg"
brew "stow"

# Apps
cask "firefox"
cask "iterm2"
cask "chromium"
cask "keepassxc"
cask "postman"

# Testing
brew "ical-buddy"
