# Neovim Stuff
brew "ripgrep"
brew "fd"
brew "taplo"

# Terminal Stuff
brew "starship"
brew "tmux"
brew "ranger"
brew "overmind"
brew "bat"

# Tmux Stuff
brew "entr"

# Version Managers
brew "git"
brew "mise"

# Other
brew "gnupg"
brew "pinentry-mac"
brew "stow"

# Apps
cask "firefox"
cask "alacritty"
cask "chromium"
cask "keepassxc"
cask "bruno"

# Testing
brew "ical-buddy"
