[tools]
usage = "latest"
ruby = "latest"
node = "latest"
neovim = "latest"
python = "latest"
perl = "latest"
pnpm = "latest"
lua-language-server = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]
