format = """
(($git_branch)( $git_commit)( $git_state)( $git_metrics)( $git_status)\n)\
(($ruby | )($nodejs | )($rust | )($golang | )($terraform | )\
($package | )$all\n)\
$directory\n\
$time $character
"""
right_format = "$cmd_duration"
command_timeout = 2000

[aws]
disabled = true

[character]
vimcmd_symbol = "[N](bold green)"
vimcmd_replace_one_symbol = "r"
vimcmd_replace_symbol = "R"
vimcmd_visual_symbol = "V"

[cmd_duration]
min_time = 200
show_milliseconds = true

[directory]
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch]($style)"

[git_commit]
format = "[\\($hash$tag\\)]($style)"
only_detached = false
tag_disabled = false

[git_metrics]
disabled = false
only_nonzero_diffs = false
format = '\([+$added]($added_style)/[-$deleted]($deleted_style)\)'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
ahead = "↑$count"
behind = "↓$count"
diverged = "↑$ahead_count↓$behind_count"
modified = "!$count"
untracked = "?$count"
stashed = "\\$$count"
staged = "+$count"

[golang]
format = "[$symbol( $version)($workspace)]($style)"
symbol = "Go"
version_format = "${raw}"

[line_break]
disabled = true

[nodejs]
format = "[$symbol( $version)]($style)"
symbol = "Node"
version_format = "${raw}"

[package]
format = "[$symbol( $version)]($style)"
symbol = "Version"

[ruby]
format = "[$symbol( $version)]($style)"
symbol = "Ruby"
version_format = "${raw}"

[rust]
format = "[$symbol( $version)]($style)"
symbol = "Rust"

[terraform]
format = "[$symbol( $workspace)]($style)"
symbol = "Terraform"
version_format = "${raw}"

[time]
disabled = false
format = '[$time]($style)'
