add_newline = false

[aws]
disabled = true

[cmd_duration]
format = " | took [$duration]($style)"

[git_metrics]
disabled = false

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
ahead = "↑$count"
behind = "↓$count"
diverged = "↑$ahead_count↓$behind_count"
modified = "!$count"
untracked = "?$count"
stashed = "\\$$count"

[nodejs]
format = " | [$symbol($version)]($style)"
symbol = "Node "
version_format = "${raw}"

[package]
format = " | [$symbol($version)]($style)"
symbol = "Version "

[ruby]
format = " | [$symbol($version)]($style)"
symbol = "Ruby "
version_format = "${raw}"

[rust]
format = " | [$symbol($version)]($style)"
symbol = "Rust "

