plugins:
- solargraph-reek
- solargraph-rails

reporters:
- reek
- require_not_found
- typecheck
- update_errors

exclude:
- "node_modules/**/*.rb"

test_coverage:
  preload_rails: false
  debug: true
